kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main

node:
  location: tokyo
  cloud: oracle

volumes:
  - name: cache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:
  - name: go-build
    image: golang:alpine
    volumes:
      - name: cache
        path: /go/pkg/mod
    commands:
      - "echo \"Runner: \" ${DRONE_STAGE_MACHINE} ${DRONE_STAGE_OS} ${DRONE_STAGE_ARCH}"
      - go env
      - apk add --no-cache git
      - go mod download
      - buildflags="-X 'main.BuildTime=`TZ=\"Asia/Shanghai\" date -Iseconds`' -X 'main.GitMessage=`git --no-pager log -1 --oneline`'" && go build -ldflags "$buildflags" -o go-bin

  - name: docker-build
    image: plugins/docker
    settings:
      repo:  cloverzrg/metrics-hub
      tags: latest
      username:
        from_secret: dockerhub-username
      password:
        from_secret: dockerhub-password

